### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by 13699531464** [EmilioCorvino/ClusteringMixedDataset#1]
could not find function "silhouette_kproto"

**Comment by EmilioCorvino** [comment]
It is defined in the clustMixType package. Did you include the library?

library("clustMixType")

**Comment by 13699531464** [comment]
Yes, I have this package, but I keep getting errors when debugging.
could not find function "silhouette_kproto".
I don’t know why this happens, and I’ve updated all the packages.

**Comment by EmilioCorvino** [comment]
I just tried cloning the repository from zero, and I am not having any issue. The only way I can replicate your problem is by removing "library("clustMixType")" and unchecking the package from PyCharm's R tools.
If that is the only error you have, it must deal with the missing package.
